Repository ReactiveX/rxjs, pull requests merged in 2018-05, with the labels that each got.

#3536 fix: fix a typing mismatch in FromEventObservable
  src/observable/FromEventObservable.ts
Labels: PR: Requires Further Review

#3667 fix(delay): fix memory leak (in stable)
  spec/operators/delay-spec.ts
  src/operators/delay.ts
Labels: Agenda Item, type: discussion

#3718 chore(test): fix operator test types e-g
  spec/operators/every-spec.ts
  spec/operators/filter-spec.ts
  spec/operators/find-spec.ts
  spec/operators/findIndex-spec.ts
  spec/operators/first-spec.ts
  spec/operators/groupBy-spec.ts
  spec/tsconfig.check.json
Labels: PR: needs rebase

#3719 chore(test): fix operator test types i-o
  spec/operators/last-spec.ts
  spec/operators/map-spec.ts
  spec/operators/max-spec.ts
  spec/operators/min-spec.ts
  spec/operators/observeOn-spec.ts
  spec/tsconfig.check.json
Labels: PR: needs rebase

#3664 fix(delayWhen): Emit source value if duration selector completes synchronously
  spec/operators/delayWhen-spec.ts
  src/internal/operators/delayWhen.ts
Labels: PR: needs rebase
