Repository ReactiveX/rxjs, pull requests merged in 2019-09, with the labels that each got.

#4977 feat(TestScheduler): expose `frameTimeFactor` property
  spec/schedulers/TestScheduler-spec.ts
  src/internal/scheduler/VirtualTimeScheduler.ts
  src/internal/testing/TestScheduler.ts
Labels: target: master only

#5021 feat(animationFrames): Adds an observable of animationFrames
  spec-dtslint/observables/dom/animationFrames-spec.ts
  spec/helpers/test-helper.ts
  spec/observables/dom/animationFrames-spec.ts
  src/index.ts
  src/internal/observable/dom/animationFrames.ts
  tsconfig.base.json
Labels: Agenda Item, target: master only

#5001 fix: missing package.json in rxjs/fetch
  .make-packages.js
Labels: target: master & patch
