Repository ReactiveX/rxjs, pull requests merged in 2020-01, with the labels that each got.

#5192 fix(pluck): fix pluck's catch-all signature for better type safety
  spec-dtslint/operators/pluck-spec.ts
  src/internal/operators/pluck.ts
Labels: target: master only, type: TS types

#5241 chore: enable TypeScript strictBindCallApply option
  spec/observables/bindCallback-spec.ts
  spec/observables/range-spec.ts
  src/internal/observable/fromEvent.ts
  src/internal/operators/combineLatest.ts
  src/internal/operators/concat.ts
  src/internal/operators/concatWith.ts
  src/internal/operators/merge.ts
  src/internal/operators/race.ts
  src/internal/operators/zip.ts
  tsconfig.json
Labels: target: master only, type: TS types

#5234 fix: don't reassign closed-over parameter in fromFetch
  spec/observables/dom/fetch-spec.ts
  src/internal/observable/dom/fetch.ts
Labels: target: master & patch

#5242 chore: tweak tsconfig options
  spec-dtslint/tsconfig.json
  tsconfig.json
Labels: target: master only, type: TS types

#5072 fix(toPromise): correct toPromise return type
  spec-dtslint/Observable-spec.ts
  src/internal/Observable.ts
Labels: target: master only
