Repository ReactiveX/rxjs, pull requests merged in 2020-04, with the labels that each got.

#5307 Stricter type definition of Subject
  docs_app/content/guide/subject.md
  spec/Subject-spec.ts
  spec/observables/from-spec.ts
  spec/operators/bufferCount-spec.ts
  spec/operators/skipUntil-spec.ts
  src/internal/Subject.ts
  src/internal/operators/repeatWhen.ts
  src/internal/operators/share.ts
  src/internal/operators/windowTime.ts
Labels: target: master only

#5299 fix(`mergeMapTo`): remove redundant/unused generic
  src/internal/operators/mergeMapTo.ts
Labels: target: master only

#4936 fix(pipe): Special handling for 0-arg case.
  spec/util/pipe-spec.ts
  src/internal/util/pipe.ts
Labels: target: master & patch

#5305 fix(fetch): don't leak event listeners added to passed-in signals
  spec/observables/dom/fetch-spec.ts
  src/internal/observable/dom/fetch.ts
Labels: target: master & patch

#5138 fix(google): Subclassing TestScheduler needs RunHelpers
  src/testing/index.ts
Labels: Patched upstream in Google

#4973 Reduce scheduler footprint for default usage of shareReplay, timeInterval, and timestamp
  integration/side-effects/snapshots/esm/websocket.js
  integration/side-effects/snapshots/esm2015/websocket.js
  integration/side-effects/snapshots/esm5/websocket.js
  spec/operators/timestamp-spec.ts
  src/internal/ReplaySubject.ts
  src/internal/operators/timestamp.ts
  src/internal/types.ts
Labels: target: master only

#4790 chore(lint): add no-unused-declaration rule
  package.json
  spec/helpers/marble-testing.ts
  spec/helpers/tests2png/diagram-test-runner.ts
  spec/helpers/tests2png/painter.ts
  spec/observables/combineLatest-spec.ts
  spec/observables/defer-spec.ts
  spec/observables/forkJoin-spec.ts
  spec/observables/fromEvent-spec.ts
  spec/observables/interval-spec.ts
  spec/observables/of-spec.ts
  spec/observables/partition-spec.ts
  spec/operators/catch-spec.ts
  spec/operators/concatMapTo-spec.ts
  spec/operators/dematerialize-spec.ts
  spec/operators/exhaust-spec.ts
  spec/operators/exhaustMap-spec.ts
  spec/operators/mergeAll-spec.ts
  spec/operators/refCount-spec.ts
  spec/operators/shareReplay-spec.ts
  spec/operators/skipUntil-spec.ts
  spec/operators/switchMapTo-spec.ts
  spec/operators/throwIfEmpty-spec.ts
  spec/operators/windowTime-spec.ts
  spec/schedulers/TestScheduler-spec.ts
  spec/subjects/BehaviorSubject-spec.ts
  src/internal/operators/combineLatestWith.ts
  src/internal/operators/defaultIfEmpty.ts
  src/internal/operators/elementAt.ts
  src/internal/operators/pluck.ts
  src/internal/operators/timeout.ts
  src/internal/operators/timeoutWith.ts
  src/internal/operators/timestamp.ts
  src/internal/util/pipe.ts
  tslint.json
Labels: target: master only

#5301 chore: remove redundant mapTo type parameters
  src/internal/operators/concatMapTo.ts
  src/internal/operators/switchMapTo.ts
Labels: target: master only

#5306 feat(fetch): add selector
  spec-dtslint/observables/dom/fetch-spec.ts
  spec-dtslint/tsconfig.json
  spec/observables/dom/fetch-spec.ts
  src/internal/observable/dom/fetch.ts
Labels: target: master & patch

#5333 refactor(subscribeToObservable): use subscribeWith util
  spec/util/subscribeWith-spec.ts
  src/internal/operators/catchError.ts
  src/internal/operators/exhaustMap.ts
  src/internal/operators/mergeMap.ts
  src/internal/operators/mergeScan.ts
  src/internal/operators/onErrorResumeNext.ts
  src/internal/operators/skipUntil.ts
  src/internal/operators/switchMap.ts
  src/internal/util/subscribeToObservable.ts
  src/internal/util/subscribeWith.ts
Labels: target: master only

#5399 fix: don't execute rescheduled animation frame and asap actions in flush
  spec/schedulers/AnimationFrameScheduler-spec.ts
  spec/schedulers/AsapScheduler-spec.ts
  src/internal/scheduler/AnimationFrameScheduler.ts
  src/internal/scheduler/AsapScheduler.ts
Labels: target: master & patch

#5287 refactor: rename Unshift to Cons
  spec-dtslint/types-spec.ts
  src/internal/operators/combineLatestWith.ts
  src/internal/operators/zipWith.ts
  src/internal/types.ts
Labels: target: master only

#5239 fix: chain subscriptions for interop with finalize
  spec/helpers/interop-helper.ts
  spec/operators/finalize-spec.ts
  src/internal/operators/finalize.ts
Labels: target: master & patch
