Repository ReactiveX/rxjs, pull requests merged in 2020-07, with the labels that each got.

#5549 fix: revert #5458
  spec/operators/shareReplay-spec.ts
  src/internal/operators/shareReplay.ts
Labels: target: master only

#5564 docs: Add the start of a glossary
  docs_app/content/guide/glossary-and-semantics.md
Labels: Agenda Item

#5497 fix(timeout): defer error creation until timeout occurs
  src/internal/operators/timeout.ts
Labels: target: master & patch

#5610 refactor: Reduce memory consumption and simplify inner and outer subscription
  spec/util/subscribeToResult-spec.ts
  src/internal/InnerSubscriber.ts
  src/internal/OuterSubscriber.ts
  src/internal/innerSubscribe.ts
  src/internal/observable/combineLatest.ts
  src/internal/observable/race.ts
  src/internal/observable/zip.ts
  src/internal/operators/audit.ts
  src/internal/operators/buffer.ts
  src/internal/operators/bufferToggle.ts
  src/internal/operators/bufferWhen.ts
  src/internal/operators/catchError.ts
  src/internal/operators/debounce.ts
  src/internal/operators/delayWhen.ts
  src/internal/operators/distinct.ts
  src/internal/operators/exhaust.ts
  src/internal/operators/exhaustMap.ts
  src/internal/operators/expand.ts
  src/internal/operators/mergeMap.ts
  src/internal/operators/mergeScan.ts
  src/internal/operators/onErrorResumeNext.ts
  src/internal/operators/repeatWhen.ts
  src/internal/operators/retryWhen.ts
  src/internal/operators/sample.ts
  src/internal/operators/skipUntil.ts
  src/internal/operators/switchMap.ts
  src/internal/operators/takeUntil.ts
  src/internal/operators/throttle.ts
  src/internal/operators/timeoutWith.ts
  src/internal/operators/window.ts
  src/internal/operators/windowToggle.ts
  src/internal/operators/windowWhen.ts
  src/internal/operators/withLatestFrom.ts
  src/internal/util/subscribeToResult.ts
Labels: target: master & patch

#5465 null out _unsubscribe after unsubscription
  spec/Subscriber-spec.ts
  spec/Subscription-spec.ts
  src/internal/Subscription.ts
Labels: target: master & patch

#5438 fix(animationFrames): emit the timestamp from the rAF's callback
  api_guard/dist/types/index.d.ts
  spec-dtslint/observables/dom/animationFrames-spec.ts
  spec/observables/dom/animationFrames-spec.ts
  src/internal/observable/dom/animationFrames.ts
Labels: target: master only
