Repository ReactiveX/rxjs, pull requests merged in 2020-05, with the labels that each got.

#5326 Fix take and takeLast
  spec/operators/take-spec.ts
  spec/operators/takeLast-spec.ts
  src/internal/operators/take.ts
  src/internal/operators/takeLast.ts
Labels: target: master only

#5325 Single operator fixes
  spec/operators/single-spec.ts
  src/index.ts
  src/internal/operators/single.ts
  src/internal/util/NotFoundError.ts
  src/internal/util/SequenceError.ts
Labels: target: master only

#5444 fix: errors thrown from iterables now properly propagated
  spec/operators/mergeMap-spec.ts
  spec/util/subscribeToResult-spec.ts
  src/internal/util/subscribeToIterable.ts
Labels: target: master & patch

#5433 fix: finalize after unsubscription from source
  spec/operators/finalize-spec.ts
  src/internal/operators/finalize.ts
Labels: target: master only

#5412 chore: add default varargs type to endWith
  spec-dtslint/operators/endWith-spec.ts
  spec-dtslint/operators/startWith-spec.ts
  src/internal/operators/endWith.ts
Labels: target: master only

#4983 test: add never dtslint tests for flattening operators
  spec-dtslint/operators/concatMap-spec.ts
  spec-dtslint/operators/concatMapTo-spec.ts
  spec-dtslint/operators/exhaustMap-spec.ts
  spec-dtslint/operators/mergeMap-spec.ts
  spec-dtslint/operators/mergeMapTo-spec.ts
  spec-dtslint/operators/switchMap-spec.ts
  spec-dtslint/operators/switchMapTo-spec.ts
Labels: target: master only

#5442 feat(fetch): add selector (cherry pick #5306 for v6)
  integration/side-effects/snapshots/esm2015/fetch.js
  spec-dtslint/observables/dom/fetch-spec.ts
  spec-dtslint/tsconfig.json
  spec/observables/dom/fetch-spec.ts
  src/internal/observable/dom/fetch.ts
Labels: target: patch only

#5457 test(shareReplay): don't restart when refCount if the source has completed
  spec/operators/shareReplay-spec.ts
Labels: target: master only

#5458 chore(shareReplay): remove redundant variable `isComplete`
  src/internal/operators/shareReplay.ts
Labels: target: master only
