Repository ReactiveX/rxjs, pull requests merged in 2020-09, with the labels that each got.

#5681 feat(onUnhandledError): configuration point added for unhandled errors
  api_guard/dist/types/index.d.ts
  spec/Observable-spec.ts
  spec/config-spec.ts
  src/internal/EMPTY_OBSERVER.ts
  src/internal/Observable.ts
  src/internal/Observer.ts
  src/internal/Subscriber.ts
  src/internal/config.ts
  src/internal/util/hostReportError.ts
  src/internal/util/reportUnhandledError.ts
  src/internal/util/subscribeToPromise.ts
  src/internal/util/toSubscriber.ts
Labels: Agenda Item

#5722 fix(scan): proper indexes when seed is not supplied
  spec/operators/scan-spec.ts
  src/internal/operators/reduce.ts
  src/internal/operators/scan.ts
Labels: PR: blocked

#5426 [docs]: Create Deprecation page per deprecation group
  docs_app/content/deprecations/scheduler-argument.md
  docs_app/content/guide/higher-order-observables.md
  docs_app/content/navigation.json
  docs_app/tools/transforms/angular-content-package/index.js
  src/internal/observable/combineLatest.ts
  src/internal/observable/concat.ts
  src/internal/observable/from.ts
  src/internal/observable/merge.ts
  src/internal/observable/of.ts
  src/internal/operators/endWith.ts
  src/internal/operators/startWith.ts
Labels: Agenda Item

#5777 docs(canonical-link): add a canonical url for rxjs.dev
  docs_app/src/app/app.component.ts
Labels: target: master & patch
