Repository ReactiveX/rxjs, pull requests merged in 2021-07, with the labels that each got.

#6488 feat: operators are all exported at the top level, from "rxjs".
  api_guard/dist/types/index.d.ts
  spec/index-spec.ts
  src/index.ts
  src/internal/symbol/observable.ts
Labels: 7.x

#6434 Core semantics
  CONTRIBUTING.md
  docs_app/content/guide/core-semantics.md
Labels: 7.x, 8.x, AGENDA ITEM

#6464 fix(debounceTime): unschedule dangling task on unsubscribe before complete
  spec/operators/debounceTime-spec.ts
  src/internal/operators/debounceTime.ts
Labels: 7.x

#6522 fix(AsyncSubject): properly emits values during reentrant subscriptions
  spec/subjects/AsyncSubject-spec.ts
  src/internal/AsyncSubject.ts
Labels: 7.x

#6531 fix: Expose `Connectable`, return type of `connectable`
  api_guard/dist/types/index.d.ts
  src/internal/observable/connectable.ts
  src/internal/types.ts
Labels: 7.x, AGENDA ITEM

#6421 feat(retry): Add configurable delay
  spec/operators/retry-spec.ts
  src/internal/operators/retry.ts
Labels: 7.x, feature

#6527 feat(tap): Adds subscribe, unsubscribe, finalize handlers
  api_guard/dist/types/index.d.ts
  api_guard/dist/types/operators/index.d.ts
  spec/operators/tap-spec.ts
  src/internal/operators/tap.ts
Labels: 7.x, AGENDA ITEM
