Repository ReactiveX/rxjs, pull requests merged in 2022-01, with the labels that each got.

#6737 docs(dematerialize): move away from bracket casts
  src/internal/operators/dematerialize.ts
Labels: 7.x, 8.x

#6710 fix(ajax): crossDomain flag deprecated and properly reported to consumers
  integration/side-effects/snapshots/esm/ajax.js
  package-lock.json
  package.json
  spec/observables/dom/ajax-spec.ts
  src/internal/ajax/ajax.ts
  src/internal/ajax/types.ts
Labels: 7.x, 8.x

#6739 docs: update operator imports in remaining examples
  docs_app/content/deprecations/multicasting.md
  docs_app/content/deprecations/resultSelector.md
  docs_app/content/deprecations/scheduler-argument.md
  docs_app/content/deprecations/to-promise.md
  docs_app/content/guide/operators.md
  docs_app/content/guide/overview.md
  docs_app/content/guide/scheduler.md
  docs_app/content/guide/subject.md
  docs_app/content/guide/testing/marble-testing.md
Labels: 7.x, 8.x

#6738 fix: use "unknown" type for operators that ignore input values
  api_guard/dist/types/index.d.ts
  api_guard/dist/types/operators/index.d.ts
  src/internal/operators/concatMapTo.ts
  src/internal/operators/ignoreElements.ts
  src/internal/operators/mapTo.ts
  src/internal/operators/mergeMapTo.ts
  src/internal/operators/switchMapTo.ts
Labels: 7.x, 8.x

#6590 Update pipe.ts
  src/internal/util/pipe.ts
Labels: 7.x, 8.x

#6541 chore: remove unused variables
  spec/helpers/marble-testing.ts
  tools/add-license-to-file.js
Labels: 7.x, 8.x

#6629 test(mocha): simplify few configurations
  .github/workflows/ci_main.yml
  spec/helpers/polyfills.ts
  spec/helpers/setup.ts
  spec/helpers/testScheduler-ui.ts
  spec/support/.mocharc.js
  wallaby.js
Labels: 7.x, 8.x

#6655 chore: fix heritage links
  docs_app/tools/transforms/templates/api/lib/memberHelpers.html
Labels: 7.x, 8.x

#6625 Remove incorrect throttleTime example
  src/internal/operators/throttleTime.ts
Labels: 7.x, 8.x

#6711 docs(operators): shareReplay refCount is false by default
  src/internal/operators/shareReplay.ts
Labels: 7.x, 8.x

#6742 docs(delay): fix marble diagram
  docs_app/src/assets/images/marble-diagrams/delay.svg
  docs_app/tools/marbles/diagrams/delay.txt
  src/internal/operators/delay.ts
Labels: 7.x, 8.x

#6746 docs: move duplicate docs from empty() to EMPTY
  src/internal/observable/empty.ts
Labels: 7.x, 8.x

#6735 feat: Remove SubscribableOrPromise type.
  api_guard/dist/types/index.d.ts
  src/internal/types.ts
Labels: 8.x

#6751 V8 remove notification
  api_guard/dist/types/index.d.ts
  api_guard/dist/types/operators/index.d.ts
  integration/side-effects/snapshots/esm/index.js
  integration/side-effects/snapshots/esm/operators.js
  integration/side-effects/snapshots/esm/testing.js
  integration/side-effects/snapshots/esm5/index.js
  integration/side-effects/snapshots/esm5/operators.js
  integration/side-effects/snapshots/esm5/testing.js
  spec-dtslint/Notification-spec.ts
  spec-dtslint/operators/dematerialize-spec.ts
  spec-dtslint/operators/materialize-spec.ts
  spec/Notification-spec.ts
  spec/index-spec.ts
  spec/operators/dematerialize-spec.ts
  spec/operators/groupBy-spec.ts
  spec/operators/materialize-spec.ts
  src/index.ts
  src/internal/Notification.ts
  src/internal/NotificationFactories.ts
  src/internal/operators/materialize.ts
Labels: AGENDA ITEM, 8.x

#6748 chore: remove deprecated subscribe use in library code
  src/internal/observable/dom/WebSocketSubject.ts
  src/internal/testing/TestScheduler.ts
Labels: 7.x, 8.x

#6753 refactor(sample): remove unnecessary variable declaration
  src/internal/operators/sample.ts
Labels: 7.x, 8.x

#6754 refactor: Remove unnecessary addition of subscription to subscriber
  spec/operators/onErrorResumeNext-spec.ts
  src/internal/operators/onErrorResumeNext.ts
Labels: 7.x, 8.x

#6736 V8 remove PromiseCtor arg from forEach
  api_guard/dist/types/index.d.ts
  spec/Observable-spec.ts
  src/internal/Observable.ts
Labels: 8.x

#6750 docs(identity): add identity docs
  src/internal/util/identity.ts
Labels: 7.x, 8.x

#6622 build(test): run mocha directly without separate transpilation
  package-lock.json
  package.json
  spec/support/.mocharc.js
  spec/support/mocha-path-mappings.js
  tsconfig.json
  tsconfig.mocha.json
Labels: 7.x, 8.x

#6757 feat(subscribe): Removed deprecated fn, fn, fn call pattern.
  api_guard/dist/types/index.d.ts
  spec-dtslint/Observable-spec.ts
  spec/Subject-spec.ts
  spec/operators/min-spec.ts
  src/internal/Observable.ts
  src/internal/Subscriber.ts
Labels: 8.x

#6759 feat(tap): Removed deprecated `tap(fn, fn, fn)` call pattern.
  api_guard/dist/types/index.d.ts
  api_guard/dist/types/operators/index.d.ts
  spec-dtslint/operators/tap-spec.ts
  src/internal/operators/tap.ts
Labels: 8.x

#6743 chore: update docs app to Angular 13
  docs_app/.gitignore
  docs_app/angular.json
  docs_app/package-lock.json
  docs_app/package.json
  docs_app/src/app/custom-elements/operator-decision-tree/operator-decision-tree.component.scss
  docs_app/src/app/shared/reporting-error-handler.ts
  docs_app/src/polyfills.ts
  docs_app/src/styles/_typography-theme.scss
  docs_app/src/styles/rxjs-theme.scss
  docs_app/src/test.ts
Labels: 7.x, 8.x
